config/routes.rb
Rails.application.routes.draw do
  get 'users/new' => 'users#new', as: :new_user
  post 'users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :posts do
    scope module: 'posts' do
      resources :corrections
      resources :claim
    end
  end

  resources :my_posts, only: %i(index)

  resources :jobs, only: %i(index)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  enum status: [:awaiting_correction, :in_correction, :awaiting_approval, :complete]
  belongs_to :user
  belongs_to :correcter, class_name: 'User', foreign_key: 'claimed_by', optional: true

  scope :awaiting_correction, -> { where(status: :awaiting_correction, corrected_text: nil) }
  scope :not_mine, -> (user_id) { where.not(user_id: user_id) }

  def self.create_with_cost(post_params)
    # TODO: save this somewhere else
    cost_per_word = 5

    Post.create(
      post_params.merge(cost_in_cents: post_params[:original_text].split.count * cost_per_word))
  end

  def word_count
    original_text.split.count
  end

  def pretty_price
    sprintf('%.2f', cost_in_cents / 100.00)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts
  has_many :jobs, class_name: 'Post', foreign_key: 'claimed_by'

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/concerns/post_scoped.rb
module PostScoped
  extend ActiveSupport::Concern

  included do
    before_action :set_post
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @posts = Post.awaiting_correction.not_mine(current_user.id)
  end
end

app/controllers/my_posts_controller.rb
class MyPostsController < ApplicationController
  def index
    @posts = current_user.posts
  end
end

app/controllers/posts/claim_controller.rb
module Posts
  class ClaimController < ApplicationController
    include PostScoped

    def create
      if @post.awaiting_correction?
        @post.update_attributes!(status: :in_correction)
        redirect_to post_corrections_path @post
      else
        flash.now.alert = 'This job was claimed. Sorry'
        redirect_to jobs_path
      end
    end
  end
end

app/controllers/posts/corrections_controller.rb
module Posts
  class CorrectionsController < ApplicationController
    include PostScoped

    def index
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.create_with_cost(post_params.merge({ user_id: current_user.id }))
    if @post.save
      redirect_to posts_url
    else
      render 'new'
    end
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update!(post_params)
    redirect_to post
  end

  private

  def post_params
    params.require(:post).permit(
      :original_text, 
      :corrected_text
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email].downcase)

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id.to_s
      redirect_to posts_path, notice: 'Logged in.'
    else
      flash.now.alert = 'Incorrect email/password combination.'
      render :new
    end
  end

  def destroy
    session.delete :user_id
    redirect_to login_path, notice: 'Logged out.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    @user.email.downcase!

    if @user.save
      flash[:notice] = 'Account successfully created!'
      redirect_to posts_url
    else
      flash.now.alert = 'Email invalid. Could not create account'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_nav.html.erb
<nav class="nav flex-column">
  <%= link_to 'New Submission', new_post_path, class: 'nav-link' %>
  <%= link_to 'All Submissions', posts_path, class: 'nav-link' %>
  <%= link_to 'Jobs', jobs_path, class: 'nav-link' %>
  <%= link_to 'My Submissions', my_posts_path, class: 'nav-link' %>
  <a class="nav-link" href="#">Account</a>
</nav>

app/views/jobs/index.html.erb
<% @posts.each do |post| %>
  <a href="<%= post_corrections_path(post) %>" class="card m-2">
    <div class="card-body p-2">
      <div class="row">
        <div class="col-10">
          <%= truncate post.original_text, length: 100 %>
        </div>
        <div class="col-2">

          <span class="badge badge-primary">
            <%= post.word_count %> words
          </span>

          <span class="badge badge-secondary">
            $<%= post.pretty_price %>
          </span>
        </div>
      </div>
    </div>
  </a>
<% end %>

<style>
.card {
  cursor: pointer; 
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Correction</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if notice %>
      <%= notice %>
    <% end %>

    <% if alert %>
      <%= alert %>
    <% end %>

    <div class="container-fluid mt-2">
      <div class="row">
        <div class="col-2">
          <%= render partial: 'nav' %>
        </div>

        <div class="col-9">
          <%= yield %>
        </div>

        <div class="col-1">
          <!-- placeholder -->
        </div>
      </div>

    </div>
  </body>
</html>

app/views/my_posts/index.html.erb
<h3>My Posts</h3>

<% @posts.each do |post| %>
  <%= render partial: 'posts/post_preview', locals: { post: post } %>
<% end %>

app/views/posts/_comparison.html.erb
<%= javascript_pack_tag 'posts' %>

<% if @post.corrected_text %>
  <div id="diff" class="min-margin">
    <h3>Comparsion</h3>
  </div>

  <hr>
<% end %>

app/views/posts/_form.html.erb
<%= form_with model: @post do |f| %>
  <div class="form-group">
    <%#= f.label :original_text %>
    <%= f.text_area :original_text, class: 'form-control', rows: 15, placeholder: 'Enter your text...' %>

  <%#= f.label :corrected_text %>
  <%#= f.text_area :corrected_text %>
  </div>

  <div class="d-flex justify-content-end">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_original_and_corrected.html.erb
<div id="original-and-corrected">
  <div class="text min-margin">
    <h3>Original</h3>
    <div id="original">
      <%= simple_format @post[:original_text] %>
    </div>
  </div>

  <div class="text min-margin">
    <h3>Corrected</h3>

    <div id="corrected">
      <%= simple_format @post[:corrected_text] || "#{@post.status.humanize}. Check back soon!" %>
    </div>
  </div>
</div>

app/views/posts/_post_preview.html.erb
<a href="<%= post_path(post) %>" class="card m-2">
  <div class="card-body p-2">
    <div class="row">
      <div class="col-10">
        <%= truncate post.original_text, length: 100 %>
      </div>
      <div class="col-2">

        <span class="badge badge-primary">
          <%= post.word_count %> words
        </span>

        <span class="badge badge-secondary">
          $<%= post.pretty_price %>
        </span>

        <span class="badge badge-secondary">
          <%= post.status.humanize %>
        </span>

      </div>
    </div>
  </div>
</a>

<style>
.card {
  cursor: pointer; 
}
</style>

app/views/posts/corrections/index.html.erb
<div class="row">
  <div class="col-6">
    <%= @post[:original_text] %>
  </div>

  <div class="col-6">
    <% if @post.in_correction? %>
      <%= form_with model: @post do |f| %>
        <div class="form-group">
          <%= f.text_area :corrected_text, class: 'form-control', rows: 15, placeholder: 'Enter your text...' %>
        </div>

        <div class="d-flex justify-content-end">
          <%= f.submit 'Submit', class: 'btn btn-primary' %>
        </div>
      <% end %>
    <% else %>
      <%= form_with url: post_claim_index_url  do |f| %>
        <%= f.submit 'Claim this job', class: 'btn btn-primary' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/corrections/show.html.erb
Post: <%= @post[:original_text] %>

app/views/posts/edit.html.erb
<%= render partial: 'form' %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <%= render partial: 'post_preview', locals: { post: post } %>
<% end %>

app/views/posts/new.html.erb
<%= render partial: 'form' %>

app/views/posts/show.html.erb
<%= render partial: 'comparison' %>
<%= render partial: 'original_and_corrected' %>

<style>
#original-and-corrected {
  display: flex;
}

.min-margin {
  margin: 8px;
}

.text {
  max-width: 400px;
}

.added {
  background: rgb(172, 242, 188);
}

.removed {
  background: rgb(253, 183, 191);
  text-decoration: line-through;
}
</style>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_with model: @user do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email, autofocus: true %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit 'Sign up' %>
<% end %>